### ISSUE TITLE
How to send Authorization header to a connection

### ISSUE THREAD

**Issue by jabrena** [steelbrain/websocket-promise#1]
Hi,

I would like to use your promise but I need to send a Authorization header.

How to do it?

Many thanks in advance.

**Comment by steelbrain** [comment]
> I would like to use your promise but I need to send a Authorization header.

Can you explain a bit more about what you mean by authorization header?

**Comment by jabrena** [comment]
Yes,

When I connect to the endpoint, I need to pass an authorization header:

```
    headers: {
        'Authorization': token_type + ' ' + access_token
    }
```

How to send this header in the connection?

**Comment by steelbrain** [comment]
I am not sure if we can do that in native websockets, besides this package just wraps around the native websockets and provides a nicer API.
Ref: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications
